name: Test and package on Linux
on: [push]
jobs:
  check-environment:
    name: Make sure environment.yml and meta.yaml are the same
    runs-on: ubuntu-18.04
    steps:
    
    - name: Check out repo
      uses: actions/checkout@v2   
      
    - name: Compare meta.yaml and environment.yml
      run: |
        gawk -f package/make_environment.awk package/conda_recipes/cytoflow/meta.yaml | gawk -f package/parse_environment.awk > env_meta
        gawk -f package/parse_environment.awk environment.yml > env_mine
        diff -u env_meta env_mine
      
  test-on-linux:
    name: Run nose2 on linux runner
    needs: check-environment
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Check out repo
      uses: actions/checkout@v2  
      
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.0.1
      with:
        activate-environment: cytoflow
        environment-file: environment.yml
    
    - name: Install package locally
      run: |
        python setup.py develop
        
    - name: Install nose2
      run: |
        pip install nose2
        
    - name: Run cytoflow tests
      env:
        OMP_NUM_THREADS: 1
      run: |
        nose2 -v -c package/nose2.cfg -s cytoflow/tests

#    - name: Run cytoflowgui tests
#      env:
#        OMP_NUM_THREADS: 1
#      run: |
#        nose2 -v -c package/nose2.cfg -s cytoflowgui/tests -GUI    

#    - name: GUI smoketest
#      run: |  
#        python --version
#        timeout -k 10 60s xvfb-run python cytoflowgui/run.py cytoflowgui/tests/startup-test.flow

    
  build-linux-conda-package:
    name: Build linux conda package
    runs-on: ubuntu-18.04
    needs: test-on-linux
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.0.1
      with:
        activate-environment: cytoflow
        environment-file: environment.yml
        
    - name: Configure conda
      run: |
        conda install --yes --quiet anaconda-client conda-build
        
    - name: Build conda package
      run: |
        conda render package/conda_recipes/cytoflow
        conda build package/conda_recipes/cytoflow
        
        
    - name: Move conda package into the dist folder
      run: |
        mkdir dist
        python package/move_conda_package.py
        
    - name: List dist
      run: ls dist/
      
    - name: Save the contents of the dist/ folder as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-conda-package
        retention-days: 1
        path: dist/*

  build-linux-wheels:
    name: Build source dist, linux wheels
    needs: test-on-linux
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Check out repo
      uses: actions/checkout@v2  
      with:
        fetch-depth: 0
      
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.0.1
      with:
        activate-environment: cytoflow
        environment-file: environment.yml
    
    - name: Install package locally
      run: |
        python setup.py develop
        
    - name: Build source dist
      run: |
        python setup.py sdist
        
    - name: Build wheel
      run: |
        python setup.py bdist_wheel
        
    - name: Move C++ extensions into the dist folder
      run: |
        cp `find build | grep "\.so$"` dist/
        
    - name: List dist
      run: ls dist/
      
    - name: Save the contents of the dist/ folder as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-wheels
        retention-days: 1
        path: dist/*   
        
  build-linux-oneclick:
    name: Build linux one-click
    needs: test-on-linux
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Check out repo
      uses: actions/checkout@v2  
      with:
        fetch-depth: 0
      
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.0.1
      with:
        activate-environment: cytoflow
        environment-file: environment.yml
    
    - name: Install package locally
      run: |
        python setup.py develop
        
    - name: Install packaging deps
      run: |
        conda install --yes --quiet 'sphinx==3.4.3'
        pip install "pyinstaller==4.1"
        
    - name: Build embedded help docs
      run: |
        python setup.py build_sphinx -b embedded_help
        
    - name: Build GUI binary
      run: |
        pyinstaller package/pyinstaller.spec
        
#    - name: GUI binary smoketest
#      run: |
#        xvfb-run dist/cytoflow/cytoflowgui ../../cytoflowgui/tests/startup-test.flow
        
    - name: List dist
      run: ls dist/
      
    - name: Save the contents of the dist/ folder as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-oneclick
        retention-days: 1
        path: dist/*
        
        
  build-examples:
    name: Zip up examples
    needs: test-on-linux
    runs-on: ubuntu-18.04
    steps:
    - name: Check out repo
      uses: actions/checkout@v2  
      with:
        fetch-depth: 0
        submodules: true

    - name: Query git tag
      id: tag
      uses: jimschubert/query-tag-action@v2
      with:
        skip-unshallow: true
        abbrev: false
        
    - name: Show Tag
      id: display
      run: |
        echo 'Output from Find Tag: ${{steps.tag.outputs.tag}}'
        
    - name: Zip up examples
      run: |
        mkdir dist
        cd docs
        zip -r cytoflow--examples-basic.zip examples-basic
        zip -r cytoflow-${{steps.tag.outputs.tag}}-examples-advanced.zip examples-advanced
        mv cytoflow-${{steps.tag.outputs.tag}}-examples-*.zip ../dist
        cd ..
        
    - name: List dist
      run: ls dist/
      
    - name: Save the contents of the dist/ folder as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: examples
        retention-days: 1
        path: dist/*
        
